# -*- coding: utf-8 -*-
"""Lesson 7 (offline) - 24.01.2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nb2vRaxf5lPAbodF0yssFtOzIA39CrC_

Topics: File I/O, Error Handling, Normalization, Aggregation.
The Task: Read inventory.txt. Some lines are corrupted.

Normalize: All item names must be Uppercase (e.g., apple becomes APPLE).

Aggregate: Sum the quantities for repeated items.

Error Handling: If the quantity is not an integer (e.g., "ten" or missing), catch the error and log the full line to audit_errors.log.

Input (inventory.txt):
> Добавить блок с цитатой

<!--
Topics: File I/O, Error Handling, Normalization, Aggregation.
The Task: Read inventory.txt. Some lines are corrupted.

Normalize: All item names must be Uppercase (e.g., apple becomes APPLE).

Aggregate: Sum the quantities for repeated items.

Error Handling: If the quantity is not an integer (e.g., "ten" or missing), catch the error and log the full line to audit_errors.log.

Input (inventory.txt):
> Добавить блок с цитатой
 -->
"""

thisdict = {}
try:
  with open('/content/inventory.txt', 'r') as f:
    for line in f:
        parts = line.strip().split(':')
        parts[0].upper()
        print(parts)
        try:
          parts[1] = int(parts[1])

          if parts[0].upper() not in thisdict:
            thisdict[parts[0].upper()] = parts[1]
          else:
            thisdict[parts[0].upper()] += parts[1]
          with open('/content/inventory.txt', 'w') as f:
            f.write(thisdict)
        except:
          with open('/content/audit_errors.log', 'a') as audit_file:
            audit_file.write("\n" + line)
except:
  print('FileNotFoundError')
# with open('inventory.txt', 'r') as f:
#     content = f.read()
#     print(content)

"""Topics: Sets, Tuples, List Filtering, File I/O.
The Task: You have a log of 12 login attempts. Some are from blacklisted IPs.

Filter: Remove any IP address present in the blacklisted_ips set.

Deduplicate: Ensure each IP appears only once.

Store: Save the safe, unique IPs into a Tuple.

Write: Write the safe IPs to authorized_logins.txt, one per line.
"""

all_logins = [
    "192.168.1.1", "10.0.0.5", "192.168.1.1", "172.16.0.1",
    "10.0.0.5", "192.168.1.10", "172.16.0.1", "8.8.8.8",
    "192.168.1.1", "10.0.0.9", "192.168.1.10", "10.0.0.5"
]
blacklisted_ips = {"172.16.0.1", "8.8.8.8", "200.50.10.1"}
new_set = set()
for ip in all_logins:
  if ip in blacklisted_ips:
    continue
  else:
    new_set.add(ip)
    print(new_set)
    with open('authorized_logins.txt', 'w') as fs:
        for i in new_set:
          fs.write(i)
          fs.write('\n')