# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16_k_asY2vrH3ChCuffCWyTUjD9c-CYFq
"""

all_logins = [
    "192.168.1.1", "10.0.0.5", "192.168.1.1", "172.16.0.1",
    "10.0.0.5", "192.168.1.10", "172.16.0.1", "8.8.8.8",
    "192.168.1.1", "10.0.0.9", "192.168.1.10", "10.0.0.5"
]
blacklisted_ips = {"172.16.0.1", "8.8.8.8", "200.50.10.1"}

safe_ips_set = set()
for ip in all_logins:
  if ip not in blacklisted_ips:
    safe_ips_set.add(ip)
    print(f"Safe and unique IPs: {safe_ips_set}")
safe_ips_tuple = tuple(safe_ips_set)
print(f"Safe and unique IPs as a tuple: {safe_ips_tuple}")
file_path = 'authorized_logins.txt'
with open(file_path, 'w') as file:
    for ip in safe_ips_tuple:
      file.write(ip + '\n')
print(f"Safe IPs written to {file_path}")
print('Verifying content of authorized_logins.txt')
with open(file_path, 'r') as file:
  content = file.read()
  print(content)

semester_1 = {
    "Alice": [85, 90], "Bob": [70, 65], "Charlie": [100],
    "David": [88], "Eve": [92, 91]
}
semester_2 = {
    "Alice": [95, 88], "Frank": [78, 80], "Bob": [72],
    "Grace": [99], "Charlie": [90, 85], "Heidi": [75]
}
merged_grades = {}

for student, grades in semester_1.items():
    merged_grades[student] = list(grades)
for student, grades in semester_2.items():
    if student in merged_grades:
        merged_grades[student].extend(grades)
    else:
        merged_grades[student] = list(grades)

print("Merged Grades:")
for student, grades in merged_grades.items():
    print(f"  {student}: {grades}")