# -*- coding: utf-8 -*-
"""Lesson 38 - QUIZ (offline) - 16.05.2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1caO4R3WY5ZmjwIAsJeKdfbzwyZCuMfOz

Exam Version B
Questions (English)
Question 1 (Regression): You are given the California Housing dataset (Link: https://www.kaggle.com/datasets/camnugent/california-housing-prices).

Task: Create a regression model to predict median house values (median_house_value).
Requirements: Perform feature engineering (handle categorical data like ocean_proximity, scale numericals). Choose an appropriate evaluation metric (RMSE). Train the model and report the metric for both the training and testing datasets.


Առաջադրանք: Ստեղծեք ռեգրեսիոն մոդել՝ տների միջին արժեքը կանխատեսելու համար (median_house_value):
Պահանջներ: Կատարեք հատկանիշների ինժեներիա (մշակեք կատեգորիալ տվյալները, օրինակ՝ ocean_proximity, ստանդարտացրեք թվային արժեքները): Ընտրեք գնահատման չափանիշ (RMSE): Ուսուցանեք մոդելը և ներկայացրեք չափանիշի արդյունքները ուսուցման (train) և թեստավորման (test) տվյալների համար։
"""

import kagglehub
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import classification_report, make_scorer, f1_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_sample_weight

# Download latest version
path = kagglehub.dataset_download("camnugent/california-housing-prices")

print("Path to dataset files:", path)
df = pd.read_csv(path + '/housing.csv')
df.head()

import joblib
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import ConfusionMatrixDisplay, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_sample_weight
from xgboost import XGBClassifier

df['total_bedrooms'] = df['total_bedrooms'].fillna(df['total_bedrooms'].median())
ocean_mapping = {
    '<1H OCEAN': 0,
    'INLAND': 1,
    'NEAR OCEAN': 2,
    'NEAR BAY': 3,
    'ISLAND': 4,
}
if "ocean_proximity" in df.columns and df["ocean_proximity"].dtype == "object":
    df["ocean_proximity"] = df["ocean_proximity"].map(ocean_mapping)

X = df.drop(columns=["ocean_proximity"])
y = df["ocean_proximity"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

sample_weights_train = compute_sample_weight(class_weight="balanced", y=y_train)

best_params = {
    "learning_rate": 0.1,
    "max_depth": 8,
    "n_estimators": 300,
    "subsample": 1.0,
    "random_state": 42,
    "eval_metric": "mlogloss",
}
final_model = XGBClassifier(**best_params)

print("⏳ Обучение ...")
final_model.fit(X_train, y_train, sample_weight=sample_weights_train)
y_pred = final_model.predict(X_test)
print("✅ Обучение завершено успешно!\n")

target_names = ["<1H OCEAN", "INLAND", "NEAR OCEAN", "NEAR BAY", "ISLAND"]
print("📊 Classification Report:")
print(classification_report(y_test, y_pred, target_names=target_names))

fig, ax = plt.subplots(figsize=(8, 8))
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=target_names)
disp.plot(cmap="Blues", ax=ax, values_format="d")
plt.title("Матрица ошибок (Confusion Matrix)", fontsize=14)
plt.show()

importances = final_model.feature_importances_
xgb_importances = pd.Series(importances, index=X.columns).sort_values(
    ascending=True
)

plt.figure(figsize=(10, 6))
xgb_importances.plot(kind="barh", color="teal")
plt.title("Важность признаков для предсказания ocean_proximity", fontsize=14)
plt.xlabel("Относительная важность (Feature Importance)", fontsize=12)
plt.grid(axis="x", linestyle="--", alpha=0.7)
plt.tight_layout()
plt.show()

joblib.dump(final_model, "xgb_ocean_model.pkl")
joblib.dump(X.columns.tolist(), "model_features.pkl")
print("💾 Модель и признаки успешно сохранены в файлы!")

df['total_bedrooms'] = df['total_bedrooms'].fillna(df['total_bedrooms'].median())
ocean_mapping = {
    '<1H OCEAN': 0,
    'INLAND': 1,
    'NEAR OCEAN': 2,
    'NEAR BAY': 3,
    'ISLAND': 4
}

df['ocean_proximity'] = df['ocean_proximity'].map(ocean_mapping)
df.head()

X = df.drop(columns=['ocean_proximity'])
y = df['ocean_proximity']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

sample_weights_train = compute_sample_weight(class_weight='balanced', y=y_train)

xgb_balanced = XGBClassifier(random_state=42, eval_metric='mlogloss') # mlogloss вместо logloss для мультикласса

param_grid = {
    'max_depth': [4, 6, 8],
    'learning_rate': [0.01, 0.05, 0.1],
    'n_estimators': [100, 200, 300],
    'subsample': [0.8, 1.0]
}

grid_balanced = GridSearchCV(
    estimator=xgb_balanced,
    param_grid=param_grid,
    scoring='f1_macro',
    cv=5,
    n_jobs=-1,
    verbose=1
)

print("⏳ Սկսվում է հավասարակշռված Grid Search-ը...")
grid_balanced.fit(X_train, y_train, sample_weight=sample_weights_train)

best_model = grid_balanced.best_estimator_
y_pred_balanced = best_model.predict(X_test)

print(f"\n✅ Լավագույն պարամետրեր: {grid_balanced.best_params_}")
print("\n📊 Հավասարակշռված Classification Report:")
print(classification_report(y_test, y_pred_balanced))

import matplotlib.pyplot as plt
import pandas as pd

importances = best_model.feature_importances_
feature_names = X.columns

xgb_importances = pd.Series(importances, index=feature_names).sort_values(ascending=True)

plt.figure(figsize=(10, 6))
xgb_importances.plot(kind='barh', color='teal')
plt.title("Важность признаков для предсказания ocean_proximity", fontsize=14)
plt.xlabel("Относительная важность (Feature Importance)", fontsize=12)
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred_balanced)

target_names = ['<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'NEAR BAY', 'ISLAND']

fig, ax = plt.subplots(figsize=(8, 8))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=target_names[:len(cm)])
disp.plot(cmap='Blues', ax=ax, values_format='d')

plt.title("Матрица ошибок (Confusion Matrix)", fontsize=14)
plt.show()









"""Exam Version B
Questions (English)
Question 2 (PCA): You are given the Wine dataset (Link: https://www.kaggle.com/datasets/brynja/wineuci).

Task: Perform dimensionality reduction using Principal Component Analysis (PCA).
Requirements: Standardize the features. Apply PCA and determine the exact number of principal components required to explain at least 85% of the total variance in the dataset. Report this number.
Հարցեր (Հայերեն)

Հարց 2 (PCA): Տրված է Wine տվյալների հավաքածուն (Հղում՝ https://www.kaggle.com/datasets/brynja/wineuci):

Առաջադրանք: Կատարեք չափողականության նվազեցում՝ կիրառելով Գլխավոր Բաղադրիչների Վերլուծություն (PCA):
Պահանջներ: Ստանդարտացրեք հատկանիշները: Կիրառեք PCA և որոշեք այն գլխավոր բաղադրիչների ճշգրիտ քանակը, որոնք անհրաժեշտ են տվյալների դիսպերսիայի (variance) առնվազն 85%-ը բացատրելու համար: Ներկայացրեք այդ քանակը:
"""

import kagglehub
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

path = kagglehub.dataset_download("brynja/wineuci")

data = pd.read_csv(path + "/Wine.csv", header=None)

X = data.drop(columns=[0])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA()
pca.fit(X_scaled)

cumulative_variance = np.cumsum(pca.explained_variance_ratio_)
n_components = np.argmax(cumulative_variance >= 0.85) + 1

print(f"Required components: {n_components}")

