# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AE5OskfR1JJ_OxQOODhRl2IR1t3K8ocj

Question 1
"""

from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd

import kagglehub

# Download latest version
path = kagglehub.dataset_download("camnugent/california-housing-prices")

print("Path to dataset files:", path)

print(os.listdir(path))

df1 = pd.read_csv(path + "/housing.csv")

df1.head()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

df1['total_bedrooms'].isnull().sum()

df1['total_rooms'].isnull().sum()

df1['total_bedrooms'] = df1['total_bedrooms'].fillna(
    df1['total_bedrooms'].median()
)

df1['total_bedrooms'].isnull().any()

df1['ocean_proximity'] = df1['ocean_proximity'].fillna(df1['ocean_proximity'].mode()[0])

from sklearn.preprocessing import LabelEncoder
leb = LabelEncoder()



df1['ocean_proximity']=leb.fit_transform(df1['ocean_proximity'])

df1.head()

cols_scale = [
    'longitude',
    'latitude',
    'housing_median_age',
    'total_rooms',
    'total_bedrooms',
    'population',
    'households',
    'median_income'
]

scaler = StandardScaler()
df1[cols_scale] = scaler.fit_transform(df1[cols_scale])

X = df1.drop(columns = "median_house_value")
y = df1["median_house_value"]

X.head()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LinearRegression
linear_reg =LinearRegression()

linear_reg.fit(X_train, y_train)

y_pred = linear_reg.predict(X_test)

from sklearn.metrics import mean_squared_error, root_mean_squared_error, r2_score, median_absolute_error, mean_absolute_error

print('mean_squared_error: ', mean_squared_error(y_test, y_pred))
print('root_mean_squared_error: ', root_mean_squared_error(y_test, y_pred))
print('r2_score: ', r2_score(y_test, y_pred))
print('median_absolute_error: ', median_absolute_error(y_test, y_pred))
print('mean_absolute_error: ', mean_absolute_error(y_test, y_pred))

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

dec_tree= DecisionTreeRegressor()
dec_tree.fit(X_train, y_train)
y_pred_dec = dec_tree.predict(X_test)

print('mean_squared_error: ', mean_squared_error(y_test, y_pred_dec))
print('root_mean_squared_error: ', root_mean_squared_error(y_test, y_pred_dec))
print('r2_score: ', r2_score(y_test, y_pred_dec))
print('median_absolute_error: ', median_absolute_error(y_test, y_pred_dec))
print('mean_absolute_error: ', mean_absolute_error(y_test, y_pred_dec))

rfr = RandomForestRegressor()
rfr.fit(X_train, y_train)
y_pred_rfr = rfr.predict(X_test)

print('mean_squared_error: ', mean_squared_error(y_test, y_pred_rfr))
print('root_mean_squared_error: ', root_mean_squared_error(y_test, y_pred_rfr))
print('r2_score: ', r2_score(y_test, y_pred_rfr))
print('median_absolute_error: ', median_absolute_error(y_test, y_pred_rfr))
print('mean_absolute_error: ', mean_absolute_error(y_test, y_pred_rfr))

gb = GradientBoostingRegressor()
gb.fit(X_train, y_train)
y_pred_gb= gb.predict(X_test)

print('mean_squared_error: ', mean_squared_error(y_test, y_pred_gb))
print('root_mean_squared_error: ', root_mean_squared_error(y_test, y_pred_gb))
print('r2_score: ', r2_score(y_test, y_pred_gb))
print('median_absolute_error: ', median_absolute_error(y_test, y_pred_gb))
print('mean_absolute_error: ', mean_absolute_error(y_test, y_pred_gb))

"""Random Forest showed the best results so far
---

Question 2
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("brynja/wineuci")

print("Path to dataset files:", path)

print(os.listdir(path))

df2 = pd.read_csv(path + "/Wine.csv")

df2.head()

df2.columns

X = df2.iloc[:, 1:]
y = df2.iloc[:, 0]

X.head()

from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix

X_scaled = scaler.fit_transform(X)

pca= PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

X_pca[:3]

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size = 0.3, random_state=44)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred_log = model.predict(X_test)

cm = confusion_matrix(y_test, y_pred_log)

cm

pca = PCA().fit(X_test)
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('number of components')
plt.ylabel('cumulative explained variance');
plt.grid(True)

"""We would need at least 4 components (or 5)"""