# -*- coding: utf-8 -*-
"""Lesson 19 (quiz - offline) - 07.03.2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rwd7K5KUM6E6deA331jX3S-ZmOKLXizI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# --- DATA SETUP ---
url = "https://raw.githubusercontent.com/bnokoro/Data-Science/master/countries%20of%20the%20world.csv"
df = pd.read_csv(url)

# Cleaning: Fix decimal commas and strip strings
cols_to_fix = ['Infant mortality (per 1000 births)', 'Birthrate', 'Phones (per 1000)', 'Service', 'Area (sq. mi.)', 'Population']
for col in cols_to_fix:
    df[col] = df[col].astype(str).str.replace(',', '.').astype(float)
df['Region'] = df['Region'].str.strip()

df.dropna(inplace = True)

df['Infant mortality (per 1000 births)']

percentile_90 = np.percentile(df['Infant mortality (per 1000 births)'], 10)
percentile_90

df['Birth_Category'] = np.where(df['Birthrate'] > 30, 'High', 'Normal')
df['Birth_Category']

filtered_df = df[(df['Region'].str.strip() == 'SUB-SAHARAN AFRICA') & (df['Phones (per 1000)'] > 100)]
filtered_df.head()

df.groupby('Region')['Service'].mean().reset_index()

plt.figure(figsize=(10, 6))
scatter = plt.scatter(df['Area (sq. mi.)'],
                      df['Population'],
                      c=df['GDP ($ per capita)'],
                      cmap='viridis',
                      alpha=0.7)

plt.xscale('log')
plt.yscale('log')
cbar = plt.colorbar(scatter)
cbar.set_label('GDP ($ per capita)')

plt.xlabel('Area (sq. mi.)')
plt.ylabel('Population')
plt.title('Area (sq. mi.) vs Population (Colored by GDP)')

ch_data = df[df['Country'].str.strip() == 'China']
if not ch_data.empty:
    plt.annotate('China',
                 xy=(ch_data['Area (sq. mi.)'].values[0], ch_data['Population'].values[0]),
                 xytext=(20, 30),
                 textcoords='offset points',
                 arrowprops=dict(arrowstyle='->', color='black'))

plt.show()