# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1REyEczeQwXaynJIrY6vkXW3A1gb8D2Yy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

url = "https://raw.githubusercontent.com/bnokoro/Data-Science/master/countries%20of%20the%20world.csv"
df = pd.read_csv(url)

# TASK 1
df['Infant mortality (per 1000 births)'] = pd.to_numeric(
    df['Infant mortality (per 1000 births)'].astype(str).str.replace(',', '.'),
    errors='coerce'
)

p = np.percentile(df['Infant mortality (per 1000 births)'].dropna(), 10)
print(p)

# TASK 2
df['Birthrate'] = pd.to_numeric(df['Birthrate'].astype(str).str.replace(',', '.'), errors='coerce')
df['Birth_Category'] = np.where(df['Birthrate'] > 30, 'High', 'Normal')
df

# TASK 3
df['Phones (per 1000)'] = df['Phones (per 1000)'].astype(str).str.replace(',', '.')
df['Phones (per 1000)'] = pd.to_numeric(df['Phones (per 1000)'], errors='coerce')

filtered = df[(df['Region'] == 'SUB-SAHARAN AFRICA') & (df['Phones (per 1000)'] > 100)]
print(filtered[['Country', 'Region', 'Phones (per 1000)']])

# TASK 4
df['Service'] = df['Service'].astype(str).str.replace(',', '.')
df['Service'] = pd.to_numeric(df['Service'],errors='coerce')

result = df.groupby('Region')['Service'].mean()

print(result)